In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('./data'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

./data\tmdb_5000_credits.csv
./data\tmdb_5000_movies.csv

In [2]:
df_movies=pd.read_csv("./data/tmdb_5000_movies.csv")
df_credits=pd.read_csv("./data/tmdb_5000_credits.csv")

In [3]:
df_movies.shape

(4803, 20)

In [4]:
df_movies.sample(5)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
724,70000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 18, ""nam...",NaN,9509,"[{""id"": 534, ""name"": ""mexico""}, {""id"": 591, ""n...",en,Man on Fire,Jaded ex-CIA operative John Creasy reluctantly...,45.299089,"[{""name"": ""Regency Enterprises"", ""id"": 508}, {...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2004-04-23,130293714,146.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,"Creasy's art is death, and he is about to pain...",Man on Fire,7.3,1553
1709,30000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 878, ...",NaN,192577,[],ja,キャプテンハーロック,Space Pirate Captain Harlock and his fearless ...,14.726338,"[{""name"": ""Toei Animation Company"", ""id"": 3116}]","[{""iso_3166_1"": ""JP"", ""name"": ""Japan""}]",2013-09-07,17137302,115.0,"[{""iso_639_1"": ""ja"", ""name"": ""\u65e5\u672c\u8a...",Released,NaN,Space Pirate Captain Harlock,6.5,356
3487,6000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 36, ""name...",NaN,13537,[],en,Shattered Glass,Fact-based 2003 drama about the young journali...,6.272570,"[{""name"": ""Lions Gate Films"", ""id"": 35}, {""nam...","[{""iso_3166_1"": ""CA"", ""name"": ""Canada""}, {""iso...",2003-11-14,2944752,94.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,NaN,Shattered Glass,6.6,111
3491,6000000,"[{""id"": 18, ""name"": ""Drama""}]",http://www.sonyclassics.com/thewackness/,13990,"[{""id"": 10683, ""name"": ""coming of age""}, {""id""...",en,The Wackness,"Set in New York City in the sweltering summer,...",7.161051,"[{""name"": ""SBK Pictures"", ""id"": 11665}, {""name...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2008-07-03,2899975,99.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,The Wackness,6.2,94
637,61000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10402, ""n...",http://www.lesmiserablesfilm.com,82695,"[{""id"": 254, ""name"": ""france""}, {""id"": 642, ""n...",en,Les Misérables,An adaptation of the successful stage musical ...,48.356214,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2012-12-18,441809770,157.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Fight. Dream. Hope. Love.,Les Misérables,7.1,1884